// <auto-generated />
using System;
using DocReservation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DocReservation.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250811172923_SeedDoctors")]
    partial class SeedDoctors
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DocReservation.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AppointmentTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("DocReservation.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Img = "/images/doctors/doc1.png",
                            Name = "Dr. Sarah Connor",
                            Specialization = "Orthopedics"
                        },
                        new
                        {
                            Id = 2,
                            Img = "/images/doctors/doc5.png",
                            Name = "Dr. John Smith",
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            Id = 3,
                            Img = "/images/doctors/doc3.png",
                            Name = "Dr. Emily Davis",
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = 4,
                            Img = "/images/doctors/doc4.png",
                            Name = "Dr. Michael Lee",
                            Specialization = "Neurology"
                        },
                        new
                        {
                            Id = 5,
                            Img = "/images/doctors/doc2.png",
                            Name = "Dr. Sophia Patel",
                            Specialization = "Dermatology"
                        },
                        new
                        {
                            Id = 6,
                            Img = "/images/doctors/doc6.png",
                            Name = "Dr. David Chen",
                            Specialization = "Gastroenterology"
                        },
                        new
                        {
                            Id = 7,
                            Img = "/images/doctors/doc7.png",
                            Name = "Dr. Martinez",
                            Specialization = "Oncology"
                        },
                        new
                        {
                            Id = 8,
                            Img = "/images/doctors/doc8.png",
                            Name = "Dr. Robert Wilson",
                            Specialization = "Endocrinology"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
